### ISSUE TITLE
LabVIEW Memory Full after running the editor for a whole day

### ISSUE THREAD

**Issue by digiajay** [JKISoftware/JKI-State-Machine-Editor#13]
SM-Editor is very helpful in probing different states during the testing phase of the application.  In one of my application, I run the testing for whole day long or two or three days.  Only small issue I find during  such extensive testing with SM-editor is, LabVIEW ends up in "memory full" error which points to the JKI state machine helper screen.  I encountered this more than three times and so I thought it's worth putting to JKI team here.  Next time if I get the error, I will put up a screenshot in this issue.

Thank you,
Ajay.

**Comment by jimkring** [comment]
I think I found the issue. This node opens a new VI reference.

![image](https://user-images.githubusercontent.com/381432/26932634-e34a3d1a-4c18-11e7-9e15-a35fdb26ddd4.png)

Here is the fix.

![image](https://user-images.githubusercontent.com/381432/26932696-1fe69e9e-4c19-11e7-9877-592efc5e10eb.png)

**Comment by jimkring** [comment]
Fixed in 2013.0.7 https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.0.7
