### ISSUE TITLE
Delete key doesn't work

### ISSUE THREAD

**Issue by joerghampel** [JKISoftware/JKI-State-Machine-Editor#15]
When selecting a case in the editor window and pressing the delete key, a dialog box appears saying "You need to select a case first".

<img width="240" alt="bildschirmfoto 2017-06-09 um 21 09 16" src="https://user-images.githubusercontent.com/7075830/26990828-5c0f1546-4d58-11e7-98ba-1aa6e93752dd.png">

**Comment by joerghampel** [comment]
This is on LV2013 SP1 (13.0.1 32bit), just in case that makes a difference.

**Comment by jimkring** [comment]
Fixed in 2013.0.8: https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.0.8

**Comment by joerghampel** [comment]
Works like a charm now - thanks for the quick resolution.
