### ISSUE TITLE
Find Callers (Find All Instance) of State

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/JKI-State-Machine-Editor#18]
Use Case: Often, when programming a JKI SM the user wants to know where a State is being called from (which other Frames).

It would be nice if there were an easy way to Find Callers (or Find All Instances) of a call to a state. This would show a Search Results dialog with a list of Instances and allow to view specific instances (by double-clicking on a result item in the list) or step through thems (e.g. using Ctrl+G like the Find >> Search Results dialog does).

This Find Callers (or Find All Instances) feature could be available from:
- Right-clicking on a State String (for the state under the mouse) and choosing "Find Callers" from the pop-up menu
- Right-clicking on a State in the SM Editor Tree View and choosing "Find Callers" from the pop-up menu
- Others?

**Comment by digiajay** [comment]
One other could be when right clicking on the case selector node and choosing "Find Callers"

**Comment by jimkring** [comment]
@digiajay Great idea. I've implemented right-click on the Case Structure. This is in release https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.1.1.130

![image](https://user-images.githubusercontent.com/381432/27546460-ac2d8462-5a47-11e7-829b-0a3db65c361b.png)
