### ISSUE TITLE
Error 1055 while reverting the VI File ->Revert...

### ISSUE THREAD

**Issue by digiajay** [JKISoftware/JKI-State-Machine-Editor#28]
If I have the state search result window open and go to revert my VI, I get the following error.

Error 1055 occurred at Close Reference in State Callers__JKI_State_Machine_Helper.vi:460009->State Callers__JKI_State_Machine_Helper.vi.ACBRProxyCaller.20002C9
Possible reason(s): LabVIEW:  Object reference is invalid.

**Comment by jimkring** [comment]
Will be fixed in next pre-release build.
