### ISSUE TITLE
Multiple instance of same SM Helper tree

### ISSUE THREAD

**Issue by digiajay** [JKISoftware/JKI-State-Machine-Editor#33]
Its good that the right click short cut menu "JKI state machine editor..." hides after I launch it using right click menu.  However, I'm still able to launch multiple instances of editor using quickdrop Ctrl+Space & Ctrl+J.  Those multiple instance editor for same state machine might confuse the user/dev.

**Comment by digiajay** [comment]
In one case, I have opened event structure editor tree (ES tree) and later opened the state machine editor tree (SM tree).  By now I got two instances of the editor tree (one for event structure and other for state machine case structure).  

In this scenario, though the ES tree responds to the tree selection, unless I choose Event case in SM tree, I wouldn't see the event structure changes.

**Comment by jimkring** [comment]
Fixed and released: https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.1.2.134

**Comment by digiajay** [comment]
Still this issue is there with 2013.1.2.134 release. I can see multiple instance is possible.

![screenshot 28-06-2017 150113](https://user-images.githubusercontent.com/6551395/27630393-00b24820-5c13-11e7-9811-9553d7d2c8f7.png)

It might help to not show JKI helper again once the helper is already opened.
 
![screenshot 28-06-2017 145753](https://user-images.githubusercontent.com/6551395/27630390-faf7354e-5c12-11e7-87f5-93f2b2d0567c.png)

**Comment by jimkring** [comment]
I'm opening this as a new (albeit related) issue: It's possible to open two instances of Editor Tree from right-click and then QD shortcut #41
