### ISSUE TITLE
Shortcut menu lists Goto %s state which can reasonably be ignored as an invalid state

### ISSUE THREAD

**Issue by digiajay** [JKISoftware/JKI-State-Machine-Editor#35]
For example, %s is used for formatting into string and on right clicking that gives Goto:%s.. Only show menu which ever state is present in JKI-SM.
![screenshot 27-06-2017 214022](https://user-images.githubusercontent.com/6551395/27597933-8817f6a8-5b81-11e7-9924-8c2e8900b3f7.png)

**Comment by jimkring** [comment]
That's good feedback, @digiajay. We should check for "%s" and not show the various state operations for that. I can't think of any other "invalid states" that might show up.

Note: We've removed the state name from the right-click menu options to keep things simpler -- that doesn't have anything to do with your request to ignore "%s" (invalid states), but it will affect your screenshot. Here's the latest version:

![image](https://user-images.githubusercontent.com/381432/27613035-3ea3bc88-5b4e-11e7-8f2e-9e9abe9ead01.png)

**Comment by jimkring** [comment]
Fixed in next release

**Comment by jimkring** [comment]
Released https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.1.2.134
