### ISSUE TITLE
Undo/Redo point lost after I switch states using editor.

### ISSUE THREAD

**Issue by digiajay** [JKISoftware/JKI-State-Machine-Editor#37]
Before using SM editor, I can undo and redo the recent changes in  VI.  However after doing some activities viz below, then it looks like my undo point and redo point are lost.

- Switch state using tree
- Goto state using context menu
- Find callers using context menu etc..,

**Comment by jimkring** [comment]
Fixed in latest release https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.1.3.150
