### ISSUE TITLE
Switching states is slower in new release

### ISSUE THREAD

**Issue by digiajay** [JKISoftware/JKI-State-Machine-Editor#39]
There is a slow response of new release 2013.1.2.134 compared to the old release 2013.1.0.107

First time slow response is acceptable, but slow response for every find is quite daunting.

Below is GIF of fast response in old version - 2013.1.0.107
![jki sm editor fast reponse](https://user-images.githubusercontent.com/6551395/27631529-5cc3a958-5c16-11e7-99b8-dfc00a8a1dee.gif)

Below is GIF of fast response in old version - 2013.1.2.134
![jki sm editor slow reponse](https://user-images.githubusercontent.com/6551395/27631581-8ab20030-5c16-11e7-853f-bed7711231b2.gif)

**Comment by digiajay** [comment]
One exception is that, if I have the Find Callers window being opened(with different calling states listed), then these event is faster as old one.

**Comment by jimkring** [comment]
That's good feedback. It's because we merged all the right-click actions into a single handler VI, so all the other code/logic is being loaded. We should move these out into separate VIs.

**Comment by jimkring** [comment]
Fixed https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.1.2.1
