### ISSUE TITLE
Missing required code

### ISSUE THREAD

**Issue by TimStahl12** [JKISoftware/JKI-State-Machine-Editor#5]
I installed the state machine editor using VIPM. No additional packages were added as I have all the prerequisite packages installed. Right-clicking on the case structure of a state machine produced the following error in a general error handler:

> Error 1003 occurred at Open VI Reference in Dynamic Launch CaseSelect__JKI_State_Machine_Helper.vi->Execute JKI SM Helper.vi
VI Path: C:\Program Files (x86)\National Instruments\LabVIEW 2015\resource\dialog\QuickDrop\plugins\_JKI State Machine Helper\CaseSelect__JKI_State_Machine_Helper.vi

The Error List shows the issue is in Mass Compile - UI - __JKI_State_Machine_Helper.vi:
SubVI 'Is Child Path__jki_lib_file.vi: SubVI is missing

The file "Is Child Path__jki_lib_file.vi" should be in ".\vi.lib\_JKI.lib\_jki_lib_file.llb\". This directory does not exist on my system. The file is not present anywhere in my LabVIEW directory.

Versions of dependencies listed in VIPM Get Info:
jki_lib_state_machine -  3.0.0.8
OpenG Application Control Library - 4.1.0.7
OpenG Comparison Library - 4.0.0.3
OpenG String Library - 4.1.0.12

**Comment by jimkring** [comment]
Thanks. Fixed in 2013.0.2.67

**Comment by jimkring** [comment]
See here: https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.0.2.67
