### ISSUE TITLE
States tree auto-expands when tree refreshes

### ISSUE THREAD

**Issue by danielnchen** [JKISoftware/JKI-State-Machine-Editor#55]
When the states tree refreshes, all items in the tree expand. The tree refreshes when states are added, removed, reordered, or renamed. 

If the user has contracted items, it may cause the user to lose their place. This can also cause the vertical scrollbar of the editor to disappear until the editor window is manually resized.

The expanded/contracted state of items in the tree should probably be persistent between refreshes

**Comment by jimkring** [comment]
Fixed in [2013.5.3.218](https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.5.3.218)
