### ISSUE TITLE
Search for Data Bundle/Unbundle [Feat. Request]

### ISSUE THREAD

**Issue by danielnchen** [JKISoftware/JKI-State-Machine-Editor#56]
Ability to search for where a data element is bundled / unbundled in the state machine.

Pops up a window just like search for state strings.

For clusters, also searches where elements of the clusters are accessed.

For elements of clusters, also searches where parent cluster is accessed.

**Comment by jimkring** [comment]
Implemented in build 2013.4.0.186 (see https://github.com/JKISoftware/JKI-State-Machine-Editor/pull/61)

**Comment by jimkring** [comment]
See Release: https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.4.0.186
