### ISSUE TITLE
Delete state at end of list behavior 

### ISSUE THREAD

**Issue by cbler** [JKISoftware/JKI-State-Machine-Editor#58]
Deleting the bottom state in the list can result in unexpected result. Specifically, the first state can end up being deleted. Seen in 2016, current work around is not to use editor for bottom states.

**Comment by jimkring** [comment]
Does this still occur?

**Comment by cbler** [comment]
Testing with 2013.4.1.190 reveals this no longer occurs.
Just installed 2013.5.0.211 and it does not occur - fixed! Thank you!

**Comment by jimkring** [comment]
Sweet! We tweaked/improved a few things under the  hood, and it must have
helped resolve this issue.

Happy JKI SM’ing!
-- 
Jim Sent from my mobile.
