### ISSUE TITLE
Walk through states in a string.

### ISSUE THREAD

**Issue by digiajay** [JKISoftware/JKI-State-Machine-Editor#59]
It would be great if we have a feature to walk through the states in a string.  Example, I would have a list of states sequenced in a macro, and I would like to walk through it just like giving Ctrl+G for walking though different search results.

**Comment by jimkring** [comment]
Great idea!

Please try out the latest release. Right click on a state string and choose Explore States.  This will open a window that looks similar to the string constant lets you navigate each of the states.

http://blog.jki.net/jki-state-machine-editor-integrated-events-and-states
