### ISSUE TITLE
State Documentation / Comments [Feature Request]

### ISSUE THREAD

**Issue by danielnchen** [JKISoftware/JKI-State-Machine-Editor#60]
Be able to see comments about a state in the state machine editor window via a tooltip.

No hover:
![image](https://user-images.githubusercontent.com/7425065/36776725-b846de92-1c1b-11e8-978f-62ca68dc201a.png)

Mouse hover:
![image](https://user-images.githubusercontent.com/7425065/36776780-e5510188-1c1b-11e8-97f1-2896b867c9e5.png)

**Comment by danielnchen** [comment]
Navigating large state machines is difficult when the state names are ambiguous or non-descriptive (deciphering someone else's code or forgetting your own)

Comments could be pulled from each state. Can parse each state for a floating comment with a particular hashtag. This will also encourage quick and better documentation.

**Comment by jimkring** [comment]
Frame documentation is now visible in the context help window when you hover over a frame name in the JKI SM Explorer tree view.
