### ISSUE TITLE
Error 1055 on Cancel while adding dynamic user event

### ISSUE THREAD

**Issue by kosist** [JKISoftware/JKI-State-Machine-Editor#66]
I experienced it with LabVIEW 2016.0f5 32 bit, JKI state machine editor v2013.5.3.218.
Steps to reproduce:
1. Right-click on the node inside the JKI state machine.
2. Select "Add Dynamic Events".
3. Then click "Cancel" in the appeared window.
4. The following error occurs:

![image](https://user-images.githubusercontent.com/1911151/38165661-4640c9c4-3517-11e8-8d6f-62f51ebfca9c.png)

**Upd**: if I select "Add Dynamic Events" from state machine helper window, and then cancel it - no error occurs.

**Comment by jimkring** [comment]
Good catch! Thanks for reporting this.
-- 
Jim Sent from my mobile.

**Comment by kosist** [comment]
Thank you, @jimkring !
There is also similar behavior, when right-click on string constant, which is not connected (directly, or via other nodes) to "Add states to the queue" node. Then, the following menu is available:
![menu](https://user-images.githubusercontent.com/1911151/38171722-af34a9fe-359f-11e8-804a-1ee77b9a4f7f.png)
And if I select some of those menu items ("Find Callers", etc.), then the same error occurs.
I guess, that this menu is also kind of a bug?

**Comment by jimkring** [comment]
Yes, that’s another bug. Good catch! Glad your helping catch all these.
Thanks.
-- 
Jim Sent from my mobile.

**Comment by jimkring** [comment]
Hi @kosist. I can't seem to reproduce this issue. Are you still able to reproduce it with the [latest release?](https://github.com/JKISoftware/JKI-State-Machine-Editor/releases)

**Comment by kosist** [comment]
Hello @jimkring. Yes, it still occurs...
![error 1055](https://user-images.githubusercontent.com/1911151/38659311-4e8f1c28-3e29-11e8-9d47-9ff9f621f757.PNG)

**Comment by kosist** [comment]
Yes, I have it enabled.
But when I disable it, the error dialog window anyway appears.
I've checked the VI where it occurs, and it seems that now reason is clear - it checks, if selected constant is "Is state string?". If no, then it does not passes string reference further, and executes next case structure, but it has empty reference as input. And at the end of the VI there is Simple Error Handler dialog window...
Should there just be connected that missing wire, or in case when it is not state string, no action should be executed at all, please?
![error dialog](https://user-images.githubusercontent.com/1911151/38663921-7ec2f9c8-3e38-11e8-9fd6-c2ce21652535.PNG)

**Comment by jimkring** [comment]
Thanks for posting that screenshot -- this makes sense and I see some other possible issues with that code that I will clean up. Thanks again!

**Comment by jimkring** [comment]
This should be fixed in [Release 2013.6.2.236](https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.6.2.236).  Would you please test and let me know how it's working for you? Thanks!

**Comment by kosist** [comment]
Hello @jimkring! Thank you, seems that now it's working without any errors.
Thank you!

**Comment by jimkring** [comment]
Great! 👍🏻
-- 
Jim Sent from my mobile.

**Comment by nitad54448** [comment]
Hi
When adding an empty JKI SM I can add dynamic events. I have a working program (a queued state machine with several loops) that is working fine. When I try to add Dynamc Events to the main JKI loop, after the animation, it throws Error 1055. LV 2017 and JKI 2018
Thanks for any clues
