### ISSUE TITLE
Insert function "Add State(s) to Queue (JKI SM)" option

### ISSUE THREAD

**Issue by kosist** [JKISoftware/JKI-State-Machine-Editor#67]
Just an idea - is it possible to implement, that at right-click on the string wire, which passes states, be accessible option to insert "Add State(s) to Queue (JKI SM)" function?
Because sometimes, when manually adding states, this function has to be added manually - so one selects it, then delete wire, puts function on block diagram, and then wire nodes.
And if one inserts it by "Insert" menu, then wire is connected to "States at back" input, and not "State(s) in" input.

**Comment by jimkring** [comment]
That’s a great idea!
-- 
Jim Sent from my mobile.

**Comment by jimkring** [comment]
Hi @kosist. FYI, this idea is on the Roadmap/Wishlist: https://github.com/JKISoftware/JKI-State-Machine-Editor/wiki/Roadmap

_Insert State into State String from right-click menu (Insert State >> Category >> State Name)._

**Comment by jimkring** [comment]
Implemented and ready for your testing and feedback.

Enjoy!

**Comment by kosist** [comment]
Thanks a lot, it works really great! Definitely I'll use it a lot!
Just one cosmetic detail, please. I attach two screenshots, where with yellow color I've highlighted wires, from where this menu could be called, and where  function will be inserted then. In case of string wires it's completely OK, because anyway when function will be inserted, code will be not broken; but if it'll be inserted to other wires datatypes (as error wire, boolean, numeric, etc.), then code will be broken.
I understand, that it's more user responsibility regarding at which node to use this function, but maybe it would be nice to limit scope of wire types from which one could call this menu option just to string wires?
What do you suggest, please?
![case 1](https://user-images.githubusercontent.com/1911151/38601088-c1a984aa-3d66-11e8-8f0f-3c4642ebb83d.PNG)
![case 2](https://user-images.githubusercontent.com/1911151/38601094-c3c5e828-3d66-11e8-8342-ad9848dda5a3.PNG)
