### ISSUE TITLE
Clicking another state when VI is running throws an error and crashes the editor

### ISSUE THREAD

**Issue by alexgieg** [JKISoftware/JKI-State-Machine-Editor#68]
Here's how to reproduce the problem with JKI State Machine Editor v2013.5.3.218 (the most recent one available from VIPM as of this post) in LabVIEW 2017 v17.0f2:

1. Open a VI with a JKI State Machine in it.
2. Right click the state machine's border and open the JKI State Machine Explorer.
3. With the Explorer open, run the VI.
4. With the VI running, go back to the block diagram.
5. In the Explorer, click any state other than the current one. The following error window will appear:
![sme_1](https://user-images.githubusercontent.com/1074619/38368962-06f06b2c-38bd-11e8-8d22-ceeb5b08c111.png)
6. Click continue.
7. Stop the VI. You'll notice the the Explorer windows is still there.
8. Open the VI again.
9. Right click the border of the state machine. You'll notice the option to open the Explorer isn't there, so you cannot open it. Other JKI State Machine Editor options do work however, but the Explorer itself is gone.
10. Close the VI.
11. Close the project (if there's one).
12. Open the project again (if there's one).
13. Open the VI.
14. Right click the border of the state machine. You'll notice the option to open the Explorer still isn't there.
15. Close the VI.
16. Close the project (if there's one).
17. Close LabVIEW itself.
18. Sometimes a small error window will appear informing you something is running and asking you whether you want to close it:
![sme_3](https://user-images.githubusercontent.com/1074619/38394753-1b44c426-3906-11e8-85a4-9ea2dbab6fc9.png)
19. Reopen LabVIEW.
20. Reopen the project (if there's one).
21. Reopen the VI.
22. The option to open the Explorer is back and it can be opened normally.

My suggestions:

- It'd be a good idea to trap these errors so that the Explorer can continue functioning afterwards.
- It'd be also a good idea for the editor to check whether the VI is running and to disable all of its state-changing functionality until it's stopped, maybe by graying out and preventing clicks anywhere on its windows.
- And it'd be extra nice to have a Tools menu option to force close and reload the whole editor in case something else goes wrong.

Thanks!

**Comment by alexgieg** [comment]
I updated the post adding the missing screenshot to step 18.

**Comment by jimkring** [comment]
Thank you for your detailed bug reports and suggestions! This makes a big
difference 😊
-- 
Jim Sent from my mobile.

**Comment by alexgieg** [comment]
You're welcome. :-)

**Comment by jimkring** [comment]
This has been fixed in release [2013.5.4.221](https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.5.4.221)
