### ISSUE TITLE
Suggestion: Add scrollbars and mouse wheel support to Explore States windows

### ISSUE THREAD

**Issue by alexgieg** [JKISoftware/JKI-State-Machine-Editor#69]
When we request an Explore States window for a big list of states, the window that opens is sometimes too small to list all the states, and it neither shows a scrollbar nor supports scrolling with the mouse wheel, so we have to manually resize the window to be able to see and interact with all the listed states:

![sme_2](https://user-images.githubusercontent.com/1074619/38370872-8ea00056-38c1-11e8-870d-02cd87073c73.png)

It'd be nice to have support for the mouse wheel added in those cases, as well as, if possible, Explore States windows first trying to auto-resize on their own up to some maximum size so as to show all or most of their listed states, with vertical and/or horizontal scrollbars appearing when a window's size isn't enough to show them all.

Thanks!

**Comment by jimkring** [comment]
That’s a great idea, Alexander. Thanks for reporting the issue/request.
-- 
Jim Sent from my mobile.

**Comment by jimkring** [comment]
This has been fixed in release [2013.5.4.221](https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.5.4.221)
