### ISSUE TITLE
Right click context menu not available for LV2013/2014.

### ISSUE THREAD

**Issue by digiajay** [JKISoftware/JKI-State-Machine-Editor#7]
No explicit menu option on right-clicking case structure in 13/14 versions.  I first saw that in LV16/15 and believed the same happens for 13/14, later found Ctrl+Space -> Ctrl+J is other shortcut.  Is it not possible to use custom menu items in 13/14 as well?

**Comment by jimkring** [comment]
I added a **BIG BOLD COMMENT** to the top of the Readme.md
https://github.com/JKISoftware/JKI-State-Machine-Editor/blob/master/README.md
