### ISSUE TITLE
Category collapses on rename

### ISSUE THREAD

**Issue by jlj-ee** [JKISoftware/JKI-State-Machine-Editor#71]
Using: LabVIEW 2016 and 2013.6.0.232

Steps to reproduce:
1. Select a category separator state in the states tree
2. Right-click -> Rename or F2
3. Enter name and press 'Ok'
4. See that the category that was just renamed has been collapsed, hiding its sub-states

Mild annoyance but hardly a showstopper. I don't seem to remember this happening in older versions. It would be ideal if the tree kept the original collapsed/expanded state through the rename.
Thanks for continuing to update this great tool!

**Comment by jlj-ee** [comment]
Actually, it seems that renaming any state (not just the category separator state) causes its category to collapse.

**Comment by jimkring** [comment]
Thanks for reporting this issue. It's been fixed in this release: https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.6.1.233
