### ISSUE TITLE
LabVIEW Crashes Reference JKI State Machine Helper

### ISSUE THREAD

**Issue by jlj-ee** [JKISoftware/JKI-State-Machine-Editor#74]
Disclaimer: I don't know much about the LabVIEW crash reports, so if this is a red herring, I apologize.

Issue: I've been seeing a noticeably higher number of LabVIEW crashes since installing the JKI State Machine Editor, typically following a right-click on the block diagram. I've started checking the crash reports, and the following is a common entry:
```
RTSetCleanupProc: leaf and root VIs in different contexts. arg=0x64800002; (Queue)
DPrintfCallChain: RTSetCleanupProc: leaf and root VIs in different contexts.
   [LinkIdentity "Check Is Helper Already Running (Get Queue)__JKI_State_Machine_Helper.vi:5680001" [ NI.LV.Dialog][LVContext "NI.LV.Dialog" (0x058543f8)]
   [LinkIdentity "Check Is Helper Already Running (Get Queue) -- Wrapper__JKI_State_Machine_Helper.vi:5100006" [ NI.LV.PopupPlugInEditPanelDiag][LVContext "NI.LV.PopupPlugInEditPanelDiag" (0x05854dd0)]
   [LinkIdentity "CaseSelect__JKI_State_Machine_Helper.vi:3490001" [ NI.LV.PopupPlugInEditPanelDiag][LVContext "NI.LV.PopupPlugInEditPanelDiag" (0x05854dd0)]
```
This is on LabVIEW 16.0f5 32-bit, Windows 10 64-bit, package version 2013.6.2.236.
As you can see, it references some JKI State Machine Helper VIs. 
Would be curious to know if others have encountered this and if it is truly related to the State Machine Editor.

**Comment by jimkring** [comment]
Thanks for reporting this. It's helpful and I've noticed an occasional LV
crash when right-clicking on things.

I'll poke around and see if there's anything that might be improved in the
code, and will ping NI about this.

**Comment by jimkring** [comment]
Hi @jlj-ee. Can you please test [Release 2013.6.3.239](https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.6.3.239) to see if crashing issue is resolved (or improved)?

**Comment by jlj-ee** [comment]
After a couple days of use, stability does seem to be improved! Thanks for that.
However, I am not able to get the 'Find Data Accessors' dialog to appear consistently now -- it appears momentarily and then disappears.

**Comment by jimkring** [comment]
@jlj-ee, I'm glad to hear the stability has improved. I'm not seeing any issues getting the 'Find Data Accessors' pop-up to open correctly.  Can you try to adjusting the [magic delay](https://blog.jki.net/news/announcing-the-new-magic-delay-fairy-tool-for-labview) (in the "Find Data Accessors" frame) in this VI to see if that helps? For example: try changing it to 500ms.

C:\Program Files (x86)\National Instruments\LabVIEW 2016\resource\plugins\PopupMenus\edit time panel and diagram\JKI SM Helper.llb\Execute JKI SM Helper - Actions.vi

![image](https://user-images.githubusercontent.com/381432/39654534-0fc0e278-4faa-11e8-8687-d5cbabc3444a.png)

**Comment by jimkring** [comment]
@jlj-ee We also heard that there may be some crashing caused by a LabVIEW issue that we might be able to fix. https://github.com/JKISoftware/JKI-State-Machine/issues/10

**Comment by jimkring** [comment]
@jlj-ee any crashing after upgrading to the latest JKI State Machine that has the editor built in (to the main package)?

**Comment by jlj-ee** [comment]
@jimkring Thanks for the heads up! I have been running an earlier JKI State Machine release with the editor built in and still occasionally seeing crashes, with no reliable way to consistently reproduce them. I will get the latest version that includes the fix to the issue you linked and see how it goes.

**Comment by jimkring** [comment]
HI @jlj-ee. Thanks for trying out the latest release (2018.0.2.37) and seeing if that fixes things for you. If it does, that would be great, since we're looking for confirmation that our recent fixes to this LabVIEW bug/crash are actually working/helpful :-)

**Comment by jlj-ee** [comment]
I've been running 2018.0.2.39 today with no crashes so far! While it was sporadic enough that it's hard to be 100% sure, I'd like to think that the changes made in 2018.0.2.37 worked. Thanks a ton @jimkring for the continued work on this even as it dove into some pretty arcane stuff!

**Comment by jimkring** [comment]
Fantastic! I’m glad to hear that you haven’t had any crashes recently.
Thanks for reporting back.
-- 
Jim Sent from my mobile.
