### ISSUE TITLE
Right-click doesn't work in LabVIEW 2014

### ISSUE THREAD

**Issue by kombela** [JKISoftware/JKI-State-Machine-Editor#78]
In LabVIEW 2014 (14.0.1) 32bit:
- Right-click doesn't open the SM editor UI, although CTRL+SPACE -> CTRL+J does open it and it is functional.
- Right-click seem to be "disabled" for all functions of the SM editor, for example for the "find data accessors".

How does it work under the hood? What should I check to help you and to find the cause or a workaround?

**Comment by jimkring** [comment]
Hi, you’re right. The right click menus only work in LabVIEW 2015 or
greater. That’s a known issue and nothing we can do about it. Thanks.
-- 
Jim Sent from my mobile.

**Comment by jimkring** [comment]
The only solution is to upgrade to LabVIEW 2015 or greater. Sorry.
-- 
Jim Sent from my mobile.
