### ISSUE TITLE
No automatic installation of add-ons dependencies along with editor installation.

### ISSUE THREAD

**Issue by digiajay** [JKISoftware/JKI-State-Machine-Editor#8]
I did not have OpenG but installed SMO in LV2013.  After launching editor (Ctrl-Space --> Ctrl-J), it started searching for missing files where I realized it needs OpenG toolkit.  Hence it failed to launch.  Then after installing OpenG, eventually editor launched successfully.  It would be nice if the dependencies are checked before installing editor.

**Comment by jimkring** [comment]
Fixed in https://github.com/JKISoftware/JKI-State-Machine-Editor/releases/tag/2013.0.5
