### ISSUE TITLE
sm editor to be used on any custom architecture that has while loop and case structure ex: producer consumer

### ISSUE THREAD

**Issue by freemason123** [JKISoftware/JKI-State-Machine-Editor#82]
SM editor is awesome.  why not make it available on any custom architecture that has a while loop and a case structure not just JKISM  like a simple producer consumer ? like how the case select plugin used to work but with all the features of SM editor.
Thanks

**Comment by jimkring** [comment]
I'm glad you like the JKI SM editor.  That's a great idea, and we'll consider it for the future. Of course, our primary focus has been to integrate the editor (which we're now calling the "JKI SM Explorer Window") ever more tightly with the JKI SM workflows  :-)
