### ISSUE TITLE
SM Explorer (12/6/2018 ver xx38) is crashing on Find Callers

### ISSUE THREAD

**Issue by arejaw** [JKISoftware/JKI-State-Machine-Editor#85]
The latest update to the JKI State machine editor is crashing with Find Callers.  It seems to find the callers - the popup box opens, then immediately closes and SME crashes.  And if there is only one caller, that frame is activated before the crash.  This is happening on two installs, both W10/LV2018 Pro.

**Comment by jimkring** [comment]
Hi @arejaw. Thanks for reporting this. I see what you're saying. A little bit of work done to improve the Find Data Accessors dialog also need to be also done in the Find Callers dialog. I'll fix that and release a new version shortly...

**Comment by jimkring** [comment]
Fixed in [JKI State Machine Release 2018.0.4.39](https://github.com/JKISoftware/JKI-State-Machine/releases/tag/2018.0.4.39). Available for download and install with VIPM.

**Comment by arejaw** [comment]
Thanks, Jim - it's working great now!
